/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/groguChair.glb --transform
Comments: WaveFront *.obj file (generated by Autodesk ATF)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/groguChair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MeshFeature1.geometry} material={nodes.MeshFeature1.material} />
    </group>
  )
}

useGLTF.preload('/groguChair-transformed.glb')
