/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Sandcrawler.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sandcrawler-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sandcrawler_Stairs.geometry} material={materials.Mat_1} />
      <mesh geometry={nodes.Sandcrawler_SmallDoor.geometry} material={materials.Mat_1} />
      <group position={[0, -1.62, 2.3]} rotation={[Math.PI / 3, 0, 0]}>
        <mesh geometry={nodes.Cylinder_Cylinder_002001.geometry} material={materials.Mat_3} />
        <mesh geometry={nodes.Cylinder_Cylinder_002001_1.geometry} material={materials.Mat_1} />
      </group>
      <mesh geometry={nodes.Sandcrawler_Tracks.geometry} material={materials.Mat_4} position={[0, 0, -0.85]} />
      <mesh geometry={nodes.Sandcrawler_Interior.geometry} material={materials.Mat_2} />
      <mesh geometry={nodes.Cylinder_017_Cylinder_006.geometry} material={materials.Mat_1} />
      <mesh geometry={nodes.Cylinder_017_Cylinder_006_1.geometry} material={materials.Mat_3} />
      <mesh geometry={nodes.Cylinder_017_Cylinder_006_2.geometry} material={materials.Mat_4} />
    </group>
  )
}

useGLTF.preload('/Sandcrawler-transformed.glb')
